spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri : http://localhost:8082
          predicates:
            - Path= /user/**
        - id: r2
          uri: http://localhost:8083
          predicates:
            - Path= /devise/**
    discovery:
      locator:
        enabled: false
server:
  port: 8888
