spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri : http://localhost:8082
          predicates:
            - Path= /user/**
        - id: r2
          uri: http://localhost:8083
          predicates:
            - Path= /devise/**
        - id: r3
          uri: http://localhost:8086
          predicates:
            - Path= /user/contracts/**
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path= /eureka/**
    discovery:
      enabled: true
server:
  port: 8888
