version: '3'
services:
  db:
    image: mysql:latest
    container_name: my_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=fatima
      - MYSQL_DATABASE=fatima
      - MYSQL_USER=fatima
      - MYSQL_PASSWORD=1234
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my_phpmyadmin
    links:
      - db:db
    ports:
      - "8080:80"
    restart: always
volumes:
  mysql_data: